### PR TITLE
Update copy for 2019

### PR DESCRIPTION
**Pull request by whyderrick**
There's a CTA that encouraged people to get involved in the current year, but it was last updated 18 months ago. There's also a mailto link that pushes to a mostly-defunct email address. This commit addresses both of those issues.

### CODE REVIEW

**Review by ckingbailey — APPROVED** [review]
Thanks for your help @whyderrick 👍

**Comment by daguar** [comment]
Just saying thanks for this! I've been running the advocacy side of this (well, also built the site back in the day) and so am using that Google list to engage residents in the implementation now that an ordinance has been passed.

As a result, I'll likely also be contributing some updates in the future.

**Comment by ckingbailey** [comment]
hey @daguar, nice to make your virtual acquaintance! It's cool to hear that you're continuing your engagement with this out the in the world

we've recently started to be concerned with a particular use case of softstory.openoakland.org. maybe you'd like to weigh in.

we regularly get emails from banks who use the page, and want more information. we believe these banks are using soft-story to make home loan decisions, i.e., soft-story appears to be being used to deny (or approve) people's home loans. what do you think? do you have any insight on this? one thing I'm wondering is if there's a way to rejigger soft-story to make it better serve residence and not banks, although we're at a total loss for actionable ideas for this. (there've been a couple ideas, but neither of them is meaningful or actionable)

**Comment by daguar** [comment]
> we regularly get emails from banks who use the page, and want more information. we believe these banks are using soft-story to make home loan decisions, i.e., soft-story appears to be being used to deny (or approve) people's home loans

Question: how many have been received? I saw one get forwarded to me, but that's it so far, so just trying to suss out outlier vs. trend.

The short version of my thoughts on improvements:
- Improve language to make clear this data has not been updated since the original survey in ~2011. Buildings may have been retrofitted since then.
  - To see whether a building has been retrofitted, one can look to the city's permits data to find a permit for retrofitting.
- Add link to new official City page for implementation https://www.oaklandca.gov/topics/SSRetrofit
  - Note the City has a more recent list available there at this link: https://cao-94612.s3.amazonaws.com/documents/List-of-Subject-Properties-05222019.pdf 

But this is also a good thing to engage with the City on. Part of the reason banks are reaching out, most likely, is that people need to borrow from a bank to do the retrofit.

Keep in mind all of these are by definition 5+ unit apartment buildings, so I think it's unlikely these are traditional home loans as you might think of them.

**Comment by ckingbailey** [comment]
Yeah, we had been wondering if this information could help people get loans to do the retrofit.

I think we get ~4 emails a year, but they've been going to an email that's not really set up for receiving so I haven't been keeping close track. I know that we have received several in my short tenure as Hack Night Lead since December.

Those are great points about data being old, and getting The City involved. Thanks!

**Pull request merged**
