### PR TITLE
Add legend to map

### LINKED ISSUE #8: Legend
from a user:
Map is very helpful - can you put with it a key explaining the check, question mark and exclamation mark?

### PR DESCRIPTION
**Pull request by zspencer**
This fixes #8. I mean, it does but is it... Legend.... Ary?!
screen shot 2014-12-02 at 8 47 42 pm

### CODE REVIEW

**Comment by daguar** [comment]
Thanks!

**Comment by daguar** [comment]
Thanks! Merged.

This is definitely an improvement, but it does show up a tad clunky (acceptably so IMHO) on iOS:

**Comment by daguar** [comment]
Argh, email image didn't show up — here it is on iOS:

softstoryios

**Comment by zspencer** [comment]
Hmm, that may be fixable with a `legend { margin-top: -2em }` or something.
Let me poke.

**Pull request merged**
